# Generated by Django 5.0.6 on 2024-07-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_date',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
