# Generated by Django 5.0.6 on 2024-07-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_birth_date_author_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True),
        ),
    ]
