# Generated by Django 5.0.6 on 2024-07-01 02:02

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[authors.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
