# Generated by Django 5.0.6 on 2024-07-03 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato xxx.xxx.xxx-xx', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
    ]
