# Generated by Django 5.0.6 on 2024-07-05 01:24

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_livro_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, validators=[books.validators.validar_isbn]),
        ),
    ]
