# Generated by Django 5.0.6 on 2024-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
