# Generated by Django 5.0.6 on 2024-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_bairro_fornecedor_cep_fornecedor_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
