# Generated by Django 5.0.6 on 2024-07-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_cnpj'),
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='fornecedores.fornecedor'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
