# Generated by Django 5.0.6 on 2024-07-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_cnpj'),
        ('pecas', '0003_fornecedor_alter_peca_nome_alter_peca_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='peca',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
