# Generated by Django 5.0.6 on 2024-07-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_alter_peca_fornecedor_peca_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
